### ISSUE TITLE
Change data model for mlp app to create Biology subclass.

### ISSUE THREAD

**Issue by dennereed** [paleocore/paleocore#27] opened 2014-10-02 21:13 UTC
We remodeled the drp app in this way and we need to do the same for mlp. Create a Biology class that is a subclass of Occurrence. Eventually we need to do the same for Archaeology and Geology as well.

**Comment by urban011** [comment] 2015-02-12 19:28
Duplicate of #39, closing.

**Closed by urban011** 2015-02-12 19:28 UTC
Labels: enhancement
